"use client";
import { FormEvent, useState } from "react";
import { MagnifyingGlassIcon, ShieldCheckIcon } from "@heroicons/react/24/outline";
import { trackingMocks, type TrackingResult } from "@/data/tracking";
import TrackingTimeline from "./TrackingTimeline";
import LoadingSpinner from "./LoadingSpinner";
import ErrorMessage from "./ErrorMessage";
import BannerAd from "./BannerAd";
import CTABanner from "./CTABanner";

export default function TrackingSearch() {
 const [code,setCode]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [result,setResult]=useState<TrackingResult|null>(null);
 const submit=(e:FormEvent)=>{e.preventDefault(); const normalized=code.trim().toUpperCase(); setError(""); setResult(null); if(!normalized){setError("Digite um código de rastreio para continuar.");return;} if(!/^[A-Z]{2}\d{9}[A-Z]{2}$/.test(normalized)){setError("Código inválido. Use o formato AA123456785BR.");return;} setLoading(true); setTimeout(()=>{setLoading(false); const found=trackingMocks[normalized]; if(found)setResult(found); else setError("Não encontramos esse código na demonstração. Teste AA123456785BR, BB987654321BR ou CC111222333BR.");},1500)};
 return <div id="rastrear" className="scroll-mt-28"><form onSubmit={submit} className="mx-auto max-w-3xl rounded-2xl bg-white p-3 shadow-2xl shadow-blue-950/20" noValidate><label htmlFor="tracking-code" className="sr-only">Código de rastreio</label><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><MagnifyingGlassIcon className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400" /><input id="tracking-code" value={code} onChange={e=>setCode(e.target.value)} placeholder="Digite seu código de rastreio (ex: AA123456785BR)" className="h-14 w-full rounded-xl border border-slate-200 bg-slate-50 pl-12 pr-4 text-slate-900 placeholder:text-slate-400 focus:border-brand-500 focus:bg-white focus:ring-4 focus:ring-blue-100" aria-describedby="tracking-help" /></div><button type="submit" disabled={loading} className="btn-primary h-14 px-8">Rastrear</button></div><p id="tracking-help" className="mt-2 flex items-center justify-center gap-1.5 text-xs text-slate-500"><ShieldCheckIcon className="h-4 w-4" />Consulta gratuita. Não armazenamos seu código.</p></form>
 <div className="mx-auto mt-6 max-w-5xl">{loading&&<LoadingSpinner/>}{error&&<ErrorMessage message={error}/>} {result&&<div className="space-y-8"><TrackingTimeline result={result}/><BannerAd size="horizontal" position="Após resultado"/><div className="grid gap-6 lg:grid-cols-2"><CTABanner eyebrow="Shopee" title="Sua encomenda está demorando?" text="Enquanto seu pacote não chega, aproveite ofertas na Shopee com frete grátis!" button="Ver ofertas na Shopee" href="https://shopee.com.br/afiliado" variant="orange"/><div className="card p-5"><BannerAd size="square" position="Oferta 300x250" /></div></div><CTABanner eyebrow="Melhor Envio" title="Vai enviar um pacote também?" text="Pessoa física também pode enviar barato. Compare PAC, SEDEX e transportadoras privadas com até 50% de desconto." button="Calcular frete agora" href="https://melhorenvio.com.br/afiliado" variant="blue"/><CTABanner eyebrow="AliExpress" title="Compre direto da China com rastreio grátis" text="Encontre produtos internacionais e acompanhe cada etapa da importação até o Brasil." button="Explorar AliExpress" href="https://aliexpress.com/afiliado" variant="light"/></div>}</div></div>;
}
